### PR TITLE
Melodic migration

### PR DESCRIPTION
**Pull request by colin-lewis-ut**
Fixed changes in dependency inheritance & issue with install space

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Three comments:

 - is fba1c6f4 supposed to be in this PR? It seems unrelated.
 - two of the commits were made with email addresses not recognised by GH. You might want to change that.
 - af3761cc appears to have different `GIT_COMMITTER_NAME` and `GIT_AUTHOR_NAME` (and perhaps the email address also)

**Comment by marip8** [comment]
We could probably drop `fba1c6f`. It was a temporary fix; I think the circle min/max areas should probably be parameterized, so I could work on that in a separate PR. Also, it seems like the changes in `ad8669f` already exist in the master branch. Not sure why they show up here as a diff.

@gavanderhoorn the intent here was not to branch this repository for Melodic, just to add a few changes that allow CI build on Melodic

**Comment by gavanderhoorn** [comment]
> the intent here was not to branch this repository for Melodic, just to add a few changes that allow CI build on Melodic

I wasn't worried or accusing you of wanting to branch :)

Just wanted to make sure we were all on the same page.

**Comment by colin-lewis-ut** [comment]
I have removed the circle area commit (to be parameterized in the future) and removed the redundant change to the install space.

**Pull request merged**
