### PR TITLE
Add Eigen dependencies to allow compilation.

### PR DESCRIPTION
**Pull request by d-walsh**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Can you give a bit more context? What platform are you trying to compile this on?

**Comment by d-walsh** [comment]
@gavanderhoorn I'm compiling on Ubuntu 16.04 + ROS Kinetic.

**Comment by marip8** [comment]
Is this PR still necessary? The repository seems to pass CI correctly on Xenial + Kinetic (as well as Bionic + Melodic) without these changes

**Comment by d-walsh** [comment]
If that’s the case then I’ll close it.

**Pull request closed without merging**
